ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

ENV RUN_TESTS=true

RUN pip3 install \
    pytest==7.4.4 \
    pytest-cov==4.1.0 \
    pytest-asyncio==0.23.8 \
    pytest-mock==3.14.0 \
    pluggy==1.5.0
